version: '3'

services:
  telegram:
    container_name: bot
    restart: unless-stopped
    build:
      context: .
    command: sh -c "python main.py"
    volumes:
      - ./files:/files
    env_file: .env